channels:
     - conda-forge
dependencies:
     - dlib
     - opencv
     - pandas==1.1.4
     - streamlit==0.82.0
     - numpy==1.19.4
     - matplotlib==3.3.1
     - scipy==1.5.3
     - imutils==0.5.3
     - pyserial==3.4
     - scikit-learn==0.23.2
